version: '3.8'

services:
  mongodb:
    image: mongo:6.0-jammy
    container_name: campusthrift-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: campusthrift-server
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: campusthrift-client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  mongo-data:
